#!/usr/bin/env python3
import json
import pathlib

ROOT = pathlib.Path('/var/lib/openclaw/bridge')
ROOT.mkdir(parents=True, exist_ok=True)

POLICY_CANDIDATES = [
    pathlib.Path('/home/node/.openclaw/bridge/command-policy.json'),  # guard container path
    pathlib.Path('/var/lib/openclaw/guard-state/bridge/command-policy.json'),  # host path
]


def load_policy_rules() -> tuple[list[dict], str]:
    for p in POLICY_CANDIDATES:
        try:
            if p.exists():
                data = json.loads(p.read_text() or '{}')
                rules = data.get('rules') if isinstance(data, dict) else None
                if isinstance(rules, list):
                    cleaned = []
                    for r in rules:
                        if not isinstance(r, dict):
                            continue
                        cleaned.append({
                            'id': r.get('id', ''),
                            'pattern': r.get('pattern', ''),
                            'decision': r.get('decision', 'ask'),
                            'description': r.get('description', ''),
                        })
                    return cleaned, str(p)
        except Exception:
            continue
    return [], 'none'


rules, source = load_policy_rules()

catalog = {
    'version': 2,
    'generatedBy': 'guard',
    'sourcePolicy': source,
    'commands': [
        {
            'name': 'command.run',
            'kind': 'command',
            'policy': 'regex-map',
            'reasonRequired': True,
            'description': 'Run strict command chains through policy map (supports ; and &&).',
            'rulesCount': len(rules),
        }
    ],
    'rules': rules,
}

(ROOT / 'commands.json').write_text(json.dumps(catalog, indent=2) + '\n')

md = [
    '# Bridge Commands (Generated by Guard)',
    '',
    f'- Policy source: `{source}`',
    f'- Rules loaded: `{len(rules)}`',
    '',
    '| Command | Policy | Description |',
    '|---|---|---|',
]
for c in catalog['commands']:
    md.append(f"| `{c['name']}` | `{c['policy']}` | {c['description']} |")

md += [
    '',
    '## Policy Rules (regex map)',
    '',
    '| Rule ID | Decision | Pattern | Description |',
    '|---|---|---|---|',
]

if rules:
    for r in rules:
        pat = (r.get('pattern') or '').replace('|', '\\|')
        desc = (r.get('description') or '').replace('|', '\\|')
        md.append(f"| `{r.get('id','')}` | `{r.get('decision','')}` | `{pat}` | {desc} |")
else:
    md.append('| _(none)_ |  |  |  |')

(ROOT / 'COMMANDS.md').write_text('\n'.join(md) + '\n')
print('ok')
