#!/usr/bin/env python3
import json, pathlib
ROOT=pathlib.Path('/var/lib/openclaw/bridge')
ROOT.mkdir(parents=True, exist_ok=True)
catalog={
  "version":1,
  "generatedBy":"guard",
  "commands":[
    {"name":"poems.read","kind":"action","policy":"approved","reasonRequired":True,"description":"Read poem of the day."},
    {"name":"poems.write","kind":"action","policy":"ask","reasonRequired":True,"description":"Write poem of the day (approval required)."},
    {"name":"poems.delete","kind":"action","policy":"rejected","reasonRequired":True,"description":"Delete poem of the day (blocked by policy)."},
    {"name":"command.run","kind":"command","policy":"regex-map","reasonRequired":True,"description":"Run strict atomic command via regex policy map."}
  ]
}
(ROOT/'commands.json').write_text(json.dumps(catalog, indent=2)+"\n")
md = [
  "# Bridge Commands (Generated by Guard)",
  "",
  "| Command | Policy | Description |",
  "|---|---|---|"
]
for c in catalog['commands']:
  md.append(f"| `{c['name']}` | `{c['policy']}` | {c['description']} |")
(ROOT/'COMMANDS.md').write_text("\n".join(md)+"\n")
print('ok')
