#!/usr/bin/env python3
import json, pathlib
ROOT=pathlib.Path('/var/lib/openclaw/bridge')
ROOT.mkdir(parents=True, exist_ok=True)
catalog={
  "version":1,
  "generatedBy":"guard",
  "commands":[
    {"name":"command.run","kind":"command","policy":"regex-map","reasonRequired":True,"description":"Run strict command chains through policy map (supports ; and &&)."}
  ]
}
(ROOT/'commands.json').write_text(json.dumps(catalog, indent=2)+"\n")
md = [
  "# Bridge Commands (Generated by Guard)",
  "",
  "| Command | Policy | Description |",
  "|---|---|---|"
]
for c in catalog['commands']:
  md.append(f"| `{c['name']}` | `{c['policy']}` | {c['description']} |")
(ROOT/'COMMANDS.md').write_text("\n".join(md)+"\n")
print('ok')
