#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
STACK_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

WORKER_WS=${WORKER_WORKSPACE_DIR:-/var/lib/openclaw/workspace}
GUARD_WS=${GUARD_WORKSPACE_DIR:-/var/lib/openclaw/guard-workspace}

sync_one() {
  local profile="$1" ws="$2"
  local core_dir="$STACK_DIR/core/$profile"

  [ -d "$core_dir" ] || return 0
  mkdir -p "$ws"

  shopt -s nullglob
  local f
  for f in "$core_dir"/*.md; do
    local name target tmp
    name=$(basename "$f")
    target="$ws/$name"
    tmp=$(mktemp)

    python3 - "$f" "$target" "$profile" <<'PY' > "$tmp"
import pathlib, re, sys
core_path=pathlib.Path(sys.argv[1])
target_path=pathlib.Path(sys.argv[2])
profile=sys.argv[3]

core=core_path.read_text() if core_path.exists() else ''

begin_core='<!-- CORE:BEGIN -->'
end_core='<!-- CORE:END -->'
begin_local='<!-- LOCAL:BEGIN -->'
end_local='<!-- LOCAL:END -->'

header=(
  '<!-- GENERATED by scripts/sync-workspaces.sh -->\n'
  f'<!-- profile={profile} source={core_path.as_posix()} -->\n\n'
)

def compose(local_text:str)->str:
    return (
        header +
        f'{begin_core}\n{core.rstrip()}\n{end_core}\n\n'
        f'{begin_local}\n{local_text.rstrip()}\n{end_local}\n'
    )

if not target_path.exists():
    print(compose(f'# Local layer for {target_path.name}\n\n(put your local, instance-specific instructions here)'))
    raise SystemExit(0)

existing=target_path.read_text()

core_re=re.compile(r'<!-- CORE:BEGIN -->.*?<!-- CORE:END -->', re.S)
local_re=re.compile(r'<!-- LOCAL:BEGIN -->(.*?)<!-- LOCAL:END -->', re.S)

if core_re.search(existing) and local_re.search(existing):
    local_body=local_re.search(existing).group(1).strip('\n')
    print(compose(local_body))
else:
    # Migrate legacy file: preserve entire current file as local layer.
    print(compose(existing.strip('\n')))
PY

    install -m 0644 "$tmp" "$target"
    rm -f "$tmp"
  done

  shopt -u nullglob
}

sync_one worker "$WORKER_WS"
sync_one guard "$GUARD_WS"

chown -R 1000:1000 "$WORKER_WS" "$GUARD_WS" 2>/dev/null || true

echo "[sync] workspaces refreshed from core profiles"
